In [72]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import joblib

In [73]:
# Load the data from a CSV file
data = pd.read_csv('weather_crop_data.csv')

In [74]:
print(data)

    Months  Max Tempt 2019  Min Tempt 2019  Max Tempt 2020  Min Tempt 2020  \
0        1           31.11           30.60           30.71           16.16
1        2           31.91           30.33           30.01           18.15
2        3           30.96           29.89           30.34           18.09
3        4           29.86           28.12           29.32           18.58
4        5           27.43           28.93           28.69           16.33
5        6           27.81           28.35           28.38           17.41
6        7           28.57           28.48           27.95           17.31
7        8           29.13           28.55           28.41           17.29
8        9           29.11           29.17           28.79           17.32
9       10           29.00           29.63           29.61           17.04
10      11           29.30           29.24           30.01           17.04
11      12           29.07           30.20           29.87           16.89

    Max Tempt 2021  Min Tempt 2021  Rainfall 2019  Rainfall 2020  \
0            17.75           16.84          67.85          77.92
1            16.63           16.49          81.13          61.76
2            18.11           17.35         137.45         126.54
3            17.17           18.07         140.86         162.75
4            17.98           17.80         156.44         121.93
5            17.17           17.08         115.27          90.89
6            17.23           16.73         110.35         184.42
7            17.27           16.67         116.54         166.52
8            17.54           17.34          97.79         128.83
9            18.25           17.38         282.29         170.92
10           17.57           17.00         147.78         120.32
11           17.24           16.92         147.29          62.05

    Rainfall 2021 Varieties of Crops grown
0           77.29                    Kales
1           78.78                    Kales
2          115.49                    Kales
3          129.93                  Cassava
4          207.38                  Sorghum
5           48.52           Sweet Potatoes
6          102.14                Sunflower
7           88.48                    Maize
8          163.06               Green Peas
9          130.90                  spinach
10         172.03                  spinach
11          67.34                  spinach

In [75]:
# Convert categorical variables to numerical using one-hot encoding
data = pd.get_dummies(data, columns=['Varieties of Crops grown'])

In [76]:
 df = pd.DataFrame

In [77]:
df = pd.DataFrame(data)

In [78]:
pd.DataFrame(data)

,Months,Max Tempt 2019,Min Tempt 2019,Max Tempt 2020,Min Tempt 2020,Max Tempt 2021,Min Tempt 2021,Rainfall 2019,Rainfall 2020,Rainfall 2021,Varieties of Crops grown_Cassava,Varieties of Crops grown_Green Peas,Varieties of Crops grown_Kales,Varieties of Crops grown_Maize,Varieties of Crops grown_Sorghum,Varieties of Crops grown_Sunflower,Varieties of Crops grown_Sweet Potatoes,Varieties of Crops grown_spinach
0,1,31.11,30.60,30.71,16.16,17.75,16.84,67.85,77.92,77.29,0,0,1,0,0,0,0,0
1,2,31.91,30.33,30.01,18.15,16.63,16.49,81.13,61.76,78.78,0,0,1,0,0,0,0,0
2,3,30.96,29.89,30.34,18.09,18.11,17.35,137.45,126.54,115.49,0,0,1,0,0,0,0,0
3,4,29.86,28.12,29.32,18.58,17.17,18.07,140.86,162.75,129.93,1,0,0,0,0,0,0,0
4,5,27.43,28.93,28.69,16.33,17.98,17.80,156.44,121.93,207.38,0,0,0,0,1,0,0,0
5,6,27.81,28.35,28.38,17.41,17.17,17.08,115.27,90.89,48.52,0,0,0,0,0,0,1,0
6,7,28.57,28.48,27.95,17.31,17.23,16.73,110.35,184.42,102.14,0,0,0,0,0,1,0,0
7,8,29.13,28.55,28.41,17.29,17.27,16.67,116.54,166.52,88.48,0,0,0,1,0,0,0,0
8,9,29.11,29.17,28.79,17.32,17.54,17.34,97.79,128.83,163.06,0,1,0,0,0,0,0,0
9,10,29.00,29.63,29.61,17.04,18.25,17.38,282.29,170.92,130.90,0,0,0,0,0,0,0,1
10,11,29.30,29.24,30.01,17.04,17.57,17.00,147.78,120.32,172.03,0,0,0,0,0,0,0,1
11,12,29.07,30.20,29.87,16.89,17.24,16.92,147.29,62.05,67.34,0,0,0,0,0,0,0,1

In [79]:
# Split the data into training and testing sets
Varieties = ['Varieties of Crops grown_Cassava','Varieties of Crops grown_Green Peas','Varieties of Crops grown_Kales','Varieties of Crops grown_Maize','Varieties of Crops grown_Sorghum','Varieties of Crops grown_Sunflower','Varieties of Crops grown_Sweet Potatoes','Varieties of Crops grown_spinach']
X = data.drop(Varieties, axis=1)
y = data[Varieties]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [80]:
# Train a random forest classifier on the training set
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

RandomForestClassifier()

In [81]:
# Evaluate the model on the testing set
y_pred = rf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0

   micro avg       0.00      0.00      0.00         3
   macro avg       0.00      0.00      0.00         3
weighted avg       0.00      0.00      0.00         3
 samples avg       0.00      0.00      0.00         3

C:\Users\OWNER\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OWNER\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OWNER\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OWNER\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [82]:
# Predict the crop type for a given month
month = pd.DataFrame({
    'Max Tempt 2019': [35],
    'Min Tempt 2019': [20],
    'Max Tempt 2020': [33],
    'Min Tempt 2020': [21],
    'Max Tempt 2021': [32],
    'Min Tempt 2021': [22],
    'Rainfall 2019': [50],
    'Rainfall 2020': [70],
    'Rainfall 2021': [60],
    'Months':[12]
})
crop_type = rf.predict(month)
print('Predicted crop type:', crop_type[0])

Predicted crop type: [0 0 0 0 0 0 0 0]

C:\Users\OWNER\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)

In [84]:
# Save the trained model to a file
joblib.dump(crop_type, 'crop_prediction_model.joblib')

['crop_prediction_model.joblib']